title: wabi sabi notes
description: an online reading journal
url: ""
baseurl: ""

collections:
  reading:
    output: true
    permalink: /reading/:name/

  notes:
    output: true
    permalink: /notes/:name/

  projects:
    output: true
    permalink: /projects/:name/
